name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
env:
  DOTNET_VERSION: '6.0.x'
  WORKING_DIRECTORY: 'code'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build project Debug
        run: dotnet publish -c Debug
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests Debug
        run: dotnet test -c Debug --no-build --verbosity normal
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build project Release
        run: dotnet publish -c Debug -o ${{ github.workspace }}/out/${{ github.event.repository.name }}
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: '${{ github.workspace }}/${{ github.event.repository.name }}.zip'
          path: ${{ github.event.repository.name }}
          directory: ${{ github.workspace }}/out
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: '${{ github.workspace }}/${{ github.event.repository.name }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
