name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
env:
  DOTNET_VERSION: '6.0.x'
  WORKING_DIRECTORY: 'code'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build project
        run: dotnet publish -c Release
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests
        run: dotnet test -c Release --no-build --verbosity normal
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Find first Release folder and .exe file
        run: |
          release_dir=$(find . -type d -name "Release" -print -quit)
          exe_dir=$(find "$release_dir" -type f -name "*.exe" -exec dirname {} \; | head -n 1)

      - name: Copy Release folder to Repo Name folder
        run: |
          mkdir -p ./${{ github.repository }}
          cp -r $release_dir/* ./${{ github.repository }}

      - name: Zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: '${{ github.repository }}.zip'
          path: ./${{ github.repository }}
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: '${{ github.repository }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
